---
title: "Within zipcode matching"
output: 
  html_document: 
    css: bodycss.css
    fig_height: 6
    fig_width: 12
    toc: yes
---
```{r echo=FALSE,warning=FALSE,message=FALSE}
rm(list=ls())
library(data.table)
library(zoo)
library(sqldf)
library(stargazer)
library(survival)
library(reshape2)
library(zipcode)
library(ggplot2)
library(sandwich)
file_path = "E:/strategic_default/"
setwd(file_path)
library(Matching)
library(zoo)

source("functions.R")
output.type = "html"
```



```{r  warning=FALSE,message=FALSE}

setwd(file_path)
zillow_cox <- readRDS(file="zillow_cox.rds")
temp <- zillow_cox[zillow_cox$ne_cutoff ==-0.2 & !is.na(zillow_cox$adjusted_mpay_rent),]
temp <- temp[!duplicated(temp[,c("loanid","ne_cutoff")]),]
temp['org_qt']<-as.yearqtr(as.Date(as.character(temp$orgdate)))
temp = temp[temp$loanterm==360,]

interestrate_zip <- readRDS("interestrate_zip.rds")
temp <- merge(temp,interestrate_zip,by=c("zip","org_qt"),all.x = TRUE)
temp['interest_diff'] <- (temp$interestrate - temp$interestrate_avg)/temp$interestrate_avg


high_mpay_rent <- temp[temp$adjusted_mpay_rent <= quantile(temp$adjusted_mpay_rent,0.95,na.rm = TRUE) & temp$adjusted_mpay_rent >= quantile(temp$adjusted_mpay_rent,0.80,na.rm = TRUE),]
high_mpay_rent['high_mpay_rent'] <- 1

low_mpay_rent <- temp[temp$adjusted_mpay_rent <= quantile(temp$adjusted_mpay_rent,0.35,na.rm = TRUE) & temp$adjusted_mpay_rent >= quantile(temp$adjusted_mpay_rent,0.05,na.rm = TRUE),]
low_mpay_rent['high_mpay_rent'] <- 0
    
temp <- rbind(high_mpay_rent,low_mpay_rent)
temp <- temp[!is.na(temp$ltv) & !is.na(temp$current_housevalue) & !is.na(temp$fico) & !is.na(temp$dti) & !is.na(temp$interestrate) & !is.na(temp$age_t),]
temp['current_hv_cat'] <- temp$current_housevalue %/% 25000
    
Tr <- temp$high_mpay_rent
Y <- temp$def

glm_prop <- glm(Tr~fico,data=temp,family = 'binomial')
propensity <- Matchby(Y=Y,Tr=Tr,by=list(temp$zip,temp$current_hv_cat,temp$ne_qt),X=glm_prop$fitted.values,M=1,replace = FALSE,print.level = 0)
#propensity <- Match(Y=Y,Tr=Tr,X=glm_prop$fitted.values,M=1,replace = FALSE)

summary(propensity)

```


```{r warning=FALSE,message=FALSE}
MatchBalance(Tr~def+org_hpi+adjusted_mpay_rent+adjusted_rent+dti+fico+ltv+interestrate_avg+current_housevalue+current_housevalue+upb,match.out = propensity,nboots = 0,data=temp,paired = TRUE)

```

```{r warning=FALSE,message=FALSE,results='asis'}

sample_matched <-rbind(temp[propensity$index.treated,],temp[propensity$index.control,])

logit <- list()
logit[[1]] <- glm(def~factor(high_mpay_rent)+factor(zip)+factor(ne_year),data=sample_matched,family = 'binomial')
logit[[2]] <- glm(def~factor(high_mpay_rent)+interest_diff+age_t+fico+ltv+dti+factor(occupancy)+factor(purpose)+factor(zip)+factor(ne_year),data=sample_matched,family = 'binomial')
logit[[3]] <- glm(def~adjusted_mpay_rent+interest_diff+age_t+fico+ltv+dti+factor(occupancy)+factor(purpose)+factor(zip)+factor(ne_year),data=sample_matched,family = 'binomial')
logit[[4]] <- glm(def~adjusted_mpay_rent2+interest_diff+age_t+fico+ltv+dti+factor(occupancy)+factor(purpose)+factor(zip)+factor(ne_year),data=sample_matched,family = 'binomial')

stargazer(logit,type = output.type,no.space = TRUE,omit = c("zip","ne_year","ne_cutoff","occupancy","purpose"),omit.labels =  c("zip","ne year","ne cutoff","occupancy","purpose"))
  
```

### Two Stage
```{r warning=FALSE,message=FALSE,results='asis',include=FALSE}
library(sem)
first_stage <- list()
first_stage[[1]] <- lm(adjusted_mpay_rent~interestrate_avg+org_hpi+factor(zip)+factor(ne_qt),data=sample_matched)
first_stage[[2]] <- lm(adjusted_mpay_rent~interestrate_avg+org_hpi+fico+ltv+dti+interest_diff+avg_school_rating+mean_forc_time+factor(recourse)+factor(occupancy)+factor(purpose)+factor(zip)*factor(ne_qt)+log(upb),data=sample_matched)
first_stage[[3]] <- lm(mpay~interestrate_avg+org_hpi,data=sample_matched)
#first_stage[[4]] <- lm(mpay~interestrate_avg+age_t*age_t+interest_diff+ltv,data=sample_matched)

stargazer(first_stage,type = output.type,no.space = TRUE,omit = c("zip","ne_qt","occupancy","purpose"),omit.labels = c("zip","ne qt","occupancy","purpose"),omit.stat = c("f","ser","rsq"))
```

```{r warning=FALSE,message=FALSE,results='asis',include=FALSE}
tsls_reg <- list()
tsls_reg[[1]] <- tsls(def ~ adjusted_mpay_rent + fico + ltv+ dti + log(upb) + interest_diff, ~ fico + ltv+ dti + log(upb) + interestrate_avg+ interest_diff + org_hpi, data=sample_matched)

summary(tsls_reg[[1]])
```

```{r warning=FALSE,message=FALSE,results='asis'}
library(AER)

iv_reg <- list()

iv_reg[[1]] <- ivreg(def ~ adjusted_mpay_rent +factor(zip) +factor(ne_year)| interestrate_avg+ org_hpi+factor(zip)+factor(ne_year) , data=sample_matched)

iv_reg[[2]] <- ivreg(def ~ adjusted_mpay_rent + fico + ltv+ dti + log(upb) + interest_diff +factor(zip)+factor(ne_year)| fico + ltv+ dti + log(upb) + interestrate_avg+ interest_diff + org_hpi +factor(occupancy) + factor(purpose)+factor(zip)+factor(ne_year), data=sample_matched)

iv_reg[[3]] <- lm(adjusted_mpay_rent~interestrate_avg+org_hpi+fico + ltv+ dti + log(upb) + interest_diff + factor(zip) ++factor(ne_year), data=sample_matched)

stargazer(iv_reg,type = output.type,no.space = TRUE,omit = c("zip","ne_year","occupancy","purpose"),omit.labels = c("zip","ne year","occupancy","purpose"),column.labels   = c("Two Stage", "First Stage"),
          column.separate = c(2, 1),omit.stat = c("f","ser","rsq"))
```

#### Without matching

```{r warning=FALSE,message=FALSE,results='asis'}
setwd(file_path)
temp <- zillow_cox[zillow_cox$ne_cutoff ==-0.2 & !is.na(zillow_cox$adjusted_mpay_rent),]
temp <- temp[!duplicated(temp[,c("loanid","ne_cutoff")]),]
temp['org_qt']<-as.yearqtr(as.Date(as.character(temp$orgdate)))
temp = temp[temp$loanterm==360,]

interestrate_zip <- readRDS("interestrate_zip.rds")
temp <- merge(temp,interestrate_zip,by=c("zip","org_qt"),all.x = TRUE)
temp['interest_diff'] <- (temp$interestrate - temp$interestrate_avg)/temp$interestrate_avg

iv_reg <- list()

iv_reg[[1]] <- ivreg(def ~ adjusted_mpay_rent +current_housevalue +factor(zip) + factor(ne_year) | interestrate_avg+org_hpi +factor(zip) + factor(ne_year), data=temp)
iv_reg[[2]] <- ivreg(def ~ adjusted_mpay_rent + fico + ltv+ dti + log(upb) + interest_diff +current_housevalue +factor(zip) + factor(ne_year)| fico + ltv+ dti + log(upb) + interestrate_avg+ interest_diff + org_hpi +factor(occupancy) + factor(purpose)+factor(zip) + factor(ne_year), data=temp)
iv_reg[[3]] <- lm(adjusted_mpay_rent~interestrate_avg+org_hpi+fico + current_housevalue+ltv+ dti + log(upb) + interest_diff + factor(zip) + factor(ne_year), data=temp)

stargazer(iv_reg,type = output.type,no.space = TRUE,omit = c("zip","ne_year","occupancy","purpose"),omit.labels = c("zip","ne year","occupancy","purpose"),column.labels   = c("Two Stage", "First Stage"),
          column.separate = c(2, 1),omit.stat = c("f","ser","rsq"))

```

